// <auto-generated />
using System;
using BoardGameFanatics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameFanatics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630003206_FixEnumTypeMapping")]
    partial class FixEnumTypeMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameFanatics.Data.CollectionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameId");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("playerId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "GameId")
                        .IsUnique();

                    b.ToTable("CollectionEntry", (string)null);
                });

            modelBuilder.Entity("BoardGameFanatics.Data.Game", b =>
                {
                    b.Property<int>("BggId")
                        .HasColumnType("integer")
                        .HasColumnName("bggId");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cachedAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageUrl");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("maxPlayers");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("minAge");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("minPlayers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PlayingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("playingTimeMinutes");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnailUrl");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("integer")
                        .HasColumnName("yearPublished");

                    b.HasKey("BggId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("BoardGameFanatics.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayName");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("\"PlayerRole\"")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("\"PlayerStatus\"")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("BoardGameFanatics.Data.CollectionEntry", b =>
                {
                    b.HasOne("BoardGameFanatics.Data.Game", "Game")
                        .WithMany("CollectionEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameFanatics.Data.Player", "Player")
                        .WithMany("CollectionEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BoardGameFanatics.Data.Game", b =>
                {
                    b.Navigation("CollectionEntries");
                });

            modelBuilder.Entity("BoardGameFanatics.Data.Player", b =>
                {
                    b.Navigation("CollectionEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
